schema:
  - graphql/*.graphql

exec:
  layout: follow-schema
  dir: internal/adapter/graphql/gateway
  filename_template: "{name}.gen.go"
  package: gateway

model:
  filename: internal/adapter/graphql/gateway/models.gen.go
  package: gateway

resolver:
  layout: follow-schema
  dir: internal/adapter/graphql/gateway
  filename_template: "{name}.resolvers.gen.go"
  package: gateway

models:
  ID:
    model:
      - github.com/99designs/gqlgen/graphql.ID
  Int:
    model:
      - github.com/99designs/gqlgen/graphql.Int32
  Int64:
    model:
      - github.com/99designs/gqlgen/graphql.Int64
  UUID:
    model:
      - github.com/99designs/gqlgen/graphql.UUID
  Uint:
    model:
      - github.com/99designs/gqlgen/graphql.Uint
