debug: false

graphql_server:
  address: "0.0.0.0"
  port: 8080
  playground: true
  query_path: "/query"
  cors:
    allowed_origins:
      - 127.0.0.1:8080
      - 0.0.0.0:8080
    allowed_methods:
      - GET
      - POST
    allowed_headers:
      - "Authentication"
    allow_credentials: false

auth:
  confirmation_code_ttl: 5m
  confirmation_template_name: confirmation_letter
  confirmation_code_subject: "ezeX confirmation code"

redis:
  host: localhost
  port: 6379
  db: 0
  password: ""
  dial_timeout: 5s
  read_timeout: 5s
  write_timeout: 5s
  pool_size: 10
  protocol: 3

notification_client:
    address: 0.0.0.0
    port: 8081