name: Lint and Format Check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Formatting and linting the project
        run: make check
